version: "3.8"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:./dev.db
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - NEXT_PUBLIC_SITE_NAME=Cynthias Hub
      - CONTACT_EMAIL=${CONTACT_EMAIL}
      - CONTACT_PHONE=${CONTACT_PHONE}
      - CONTACT_LINKEDIN=${CONTACT_LINKEDIN}
    volumes:
      - ./:/app
    command: sh -c "npx prisma generate && npm run start"