services:
  web:
    build: .
    image: ghcr.io/Udie-Cynthia/cynthias-hub:clean-main
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - HOST=0.0.0.0
    volumes:
      - ./public/uploads:/app/public/uploads
    restart: unless-stopped
